Simplify script
Signed-off-by: Arthit Suriyawongkul <arthit@gmail.com>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -66,66 +66,44 @@ jobs:
       - name: Validate SPDX 2.2 & SPDX 2.3 Documents
         run: |
           set +e
-          EXIT_CODE=0
-          TOTAL_COUNT=0
-          PASSED_COUNT=0
-          FAILURE_COUNT=0
-          FAILED_FILES=""
+          FAIL_COUNT=0
+          FAIL_FILES=""
 
           for f in $(find . \( -path '*/spdx2.2/*' -o -path '*/spdx2.3/*' \) \( -name *.spdx -o -name *.json \)); do
               echo "$f"
-              TOTAL_COUNT=$((TOTAL_COUNT + 1))
               java -jar tools-java.jar Verify "$f"
-              if [ $? -eq 0 ]; then
-                  PASSED_COUNT=$((PASSED_COUNT + 1))
-              else
-                  FAILURE_COUNT=$((FAILURE_COUNT + 1))
-                  FAILED_FILES="$FAILED_FILES\n$f"
-                  EXIT_CODE=1
+              if [ $? -neq 0 ]; then
+                  FAIL_COUNT=$((FAIL_COUNT + 1))
+                  FAIL_FILES="$FAIL_FILES\n$f"
               fi
           done
 
-          echo ""
-          echo "Files tested: $TOTAL_COUNT"
-          echo "Files passed: $PASSED_COUNT"
-          echo "Files failed: $FAILURE_COUNT"
-
-          if [ $FAILURE_COUNT -ne 0 ]; then
+          if [ $FAIL_COUNT -ne 0 ]; then
               echo ""
-              echo -n "Failed files:"
-              echo -e "$FAILED_FILES"
-          fi
-
-          if [ $EXIT_CODE -ne 0 ]; then
-              exit $EXIT_CODE
+              echo "Files failed: $FAIL_COUNT"
+              echo -e "$FAIL_FILES"
+              exit 1
           fi
 
       - name: Validate SPDX 3.0 Documents
         run: |
+          set +e
+          FAIL_COUNT=0
+          FAIL_FILES=""
+
           for f in $(find . -type f -path '*/spdx3.0/*.json'); do
               echo "$f"
-              TOTAL_COUNT=$((TOTAL_COUNT + 1))
               spdx3-validate -j $f
-              if [ $? -eq 0 ]; then
-                  PASSED_COUNT=$((PASSED_COUNT + 1))
-              else
-                  FAILURE_COUNT=$((FAILURE_COUNT + 1))
-                  FAILED_FILES="$FAILED_FILES\n$f"
+              if [ $? -ne 0 ]; then
+                  FAIL_COUNT=$((FAIL_COUNT + 1))
+                  FAIL_FILES="$FAIL_FILES\n$f"
                   EXIT_CODE=1
               fi
           done
 
-          echo ""
-          echo "Files tested: $TOTAL_COUNT"
-          echo "Files passed: $PASSED_COUNT"
-          echo "Files failed: $FAILURE_COUNT"
-
-          if [ $FAILURE_COUNT -ne 0 ]; then
+          if [ $FAIL_COUNT -ne 0 ]; then
               echo ""
-              echo -n "Failed files:"
-              echo -e "$FAILED_FILES"
-          fi
-
-          if [ $EXIT_CODE -ne 0 ]; then
-              exit $EXIT_CODE
+              echo "Files failed: $FAIL_COUNT"
+              echo -e "$FAIL_FILES"
+              exit 1
           fi
