Continue validate 3.0 even 2.x validation failed
Signed-off-by: Arthit Suriyawongkul <arthit@gmail.com>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -63,7 +63,8 @@ jobs:
           python3 -m pip install -U pip
           python3 -m pip install spdx3-validate
 
-      - name: Validate SPDX documents
+      - name: Validate SPDX 2.2 & SPDX 2.3 Documents
+        continue-on-error: true
         run: |
           set +e
           EXIT_CODE=0
@@ -85,6 +86,23 @@ jobs:
               fi
           done
 
+          echo ""
+          echo "Files tested: $TOTAL_COUNT"
+          echo "Files passed: $PASSED_COUNT"
+          echo "Files failed: $FAILURE_COUNT"
+
+          if [ $FAILURE_COUNT -ne 0 ]; then
+              echo ""
+              echo "Failed files:"
+              echo -e "$FAILED_FILES"
+          fi
+
+          if [ $EXIT_CODE -ne 0 ]; then
+              exit $EXIT_CODE
+          fi
+
+      - name: Validate SPDX 3.0 Documents
+        run: |
           for f in $(find . -type f -path '*/spdx3.0/*.json'); do
               echo "Checking $f..."
               TOTAL_COUNT=$((TOTAL_COUNT + 1))
